name: runGenerateReports

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  
  getMissingCountries:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Get Data
        run: |
          cd data
          curl -O https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/new_cases.csv
          
      - name: Analyze Data
        run: |
          python src/getMissingCountries.py

      - uses: EndBug/add-and-commit@v9 
        with:
          add: 'docs'
                
