name: runGenerateReports

on:
  schedule:
    - cron: '0 1 * * *'
  
  workflow_run:
    workflows: [updateCountries]
    types:
      - completed
      
  workflow_dispatch:

jobs:
  
  getDataAndGenerateReports:
    runs-on: ubuntu-20.04

    steps:
    
      - uses: actions/checkout@v3

      - name: Get Data
        run: |
          cd data
          curl -O https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/new_cases.csv
          curl -O https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv
          curl -O https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/total_cases.csv
          
      - name: Analyze Data
        run: |
          cd src
          python getMissingCountries.py
          python getLatestDataForCountries.py

      - uses: EndBug/add-and-commit@v9 
        with:
          add: 'docs'
                
