name: updateCountriesAndRun

on:
  
  workflow_dispatch:
    inputs:
      countries:
        description: "List of Countries"
        required: true
        type: string
      
jobs:

  getCountries:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Handle input
        run: |
          echo "Countries:" ${{ inputs.countries }}
          rm data/countries.txt
          cd src
          python handleCountries.py ${{ inputs.countries }}
            
      - uses: EndBug/add-and-commit@v9 
        with:
          add: 'data/countries.txt'
      
          


